### ISSUE TITLE
C++ function call with parameter

### ISSUE THREAD

**Issue by StefanTrifunovic** [matt-attack/Jet#2]
I want to call script function and pass parameter to it, but it returns **Null** . I don't know if my JetContext call is wrong, so I hope this can be resolved. Here's example from my test :

Call from c++ : 
```cpp
// Don't know if this is a right way to pass parameters to script function
_ScriptContext->Call("onUpdate", new Jet::Value(dt),1); // dt is float

```

Script : 
```javascript
fun onUpdate(delta)
{
	print(delta);
} 
```
Return in console : **Null**

Thanks in advance

**Comment by matt-attack** [comment]
Working on an update to fix this. Will be up in a little bit.

**Comment by matt-attack** [comment]
Commit pushed with a fix. Thanks for the heads up.
Make sure you delete the data you pass to Call afterwards or else it will leak.
