### ISSUE TITLE
Negative function parameter

### ISSUE THREAD

**Issue by StefanTrifunovic** [matt-attack/Jet#4]
When you add negative function parameter to a script command, I lost some values in c++. Here's an example :

I have a script command, and second parameter of that command is negative number(**-100**).
```js
effect_move("bat",-100,120,6);
```
The output returns first parameter, which is a string as number, same as second parameter. 
```c++
(*_ScriptContext)["effect_move"] = [](Jet::JetContext* context, Jet::Value* arguments, int numarguments)
{
		Jet::Value a = arguments[0];   // Number , -100 <- Lost string value
		Jet::Value b = arguments[1];   // Number , -100
		Jet::Value c = arguments[2];   // Number , 120
		Jet::Value d = arguments[3];   // Number , 6
};
```

But when you use negative number as variable(**num**), everything works ok.
```js
	num = -100;
	effect_move("bat",num,120,6);
```
```c++
(*_ScriptContext)["effect_move"] = [](Jet::JetContext* context, Jet::Value* arguments, int numarguments)
{
		Jet::Value a = arguments[0];   // String, "bat" <- OK 
		Jet::Value b = arguments[1];   // Number , -100
		Jet::Value c = arguments[2];   // Number , 120
		Jet::Value d = arguments[3];   // Number , 6
};
```

ps. keep up the good work, this scripting language rocks !

**Comment by matt-attack** [comment]
Fixed. New commit resolves related issues with unary operators and negative constants.
Thanks!
